/**
 * "Start in Parallel Code" from Super Productivity: a `parallelcode://` link
 * parks a Super Productivity task id in the main process; this pulls it,
 * fetches the task and pre-fills the New Task panel. Nothing starts until the
 * user submits the form.
 */
import { invoke } from '../lib/ipc';
import { IPC } from '../../electron/ipc/channels';
import { warn as logWarn } from '../lib/log';
import { store, setStore } from './core';
import { setActiveTask, toggleNewTaskPanel } from './navigation';
import { showNotification } from './notification';
import {
  buildPromptFromSpTask,
  toSpTitle,
  type SpFailureReason,
  type SpResult,
  type SpTaskDetail,
} from '../../electron/shared/super-productivity';
import { onTaskRenamed, setProjectSpMapping, setSpLink } from './superProductivity';
import type { SpNewTaskSource } from './types';

function failureMessage(reason: SpFailureReason): string {
  switch (reason) {
    case 'not_configured':
      return 'Connect Super Productivity in Settings to open its tasks here';
    case 'disabled':
      return 'Turn on the Local REST API in Super Productivity’s settings';
    case 'unauthorized':
      return 'Super Productivity rejected the access token — update it in Settings';
    case 'not_found':
      return 'That task no longer exists in Super Productivity';
    case 'not_ready':
      return 'Super Productivity is still starting — try again in a moment';
    case 'unreachable':
      // Super Productivity stops listening when the API is off, so an API
      // that was never turned on looks exactly like the app not running.
      return 'Could not reach Super Productivity — is it running, with its Local REST API turned on?';
    default:
      return 'Could not load the task from Super Productivity';
  }
}

/** Super Productivity's catch-all project; a pairing learned from it would stick. */
const SP_INBOX_PROJECT_ID = 'INBOX_PROJECT';

async function openNewTaskFromSp(spTaskId: string): Promise<void> {
  // Already has a task here: go to it rather than creating a second one. Needs
  // nothing from Super Productivity. A task whose close failed is still here.
  const existing = Object.values(store.tasks).find(
    (task) =>
      task.superProductivity?.taskId === spTaskId &&
      task.closingStatus !== 'closing' &&
      task.closingStatus !== 'removing',
  );
  if (existing) {
    // Expanding a collapsed task restarts its agents; leave that to the user.
    if (existing.collapsed) showNotification(`“${existing.name}” is collapsed in Parallel Code`);
    else setActiveTask(existing.id);
    return;
  }

  // Checked before any state is set: the form cannot open without a project,
  // and a pre-fill left behind would attach to whatever task is created next.
  if (!store.projects.some((p) => (p.kind ?? 'code') === 'code')) {
    showNotification('Add a project to Parallel Code first');
    return;
  }
  if (store.showNewTaskPanel) {
    showNotification('Finish or close the open New Task form first');
    return;
  }

  const res = await invoke<SpResult<SpTaskDetail>>(IPC.SuperProductivityGetTask, {
    taskId: spTaskId,
    includeIssueUrl: true,
  });
  if (!res.ok) {
    showNotification(failureMessage(res.reason));
    return;
  }
  const spTask = res.value;
  // The form may have been opened while the task loaded.
  if (store.showNewTaskPanel) {
    showNotification('Finish or close the open New Task form first');
    return;
  }
  const projectId =
    store.projects.find(
      (p) =>
        spTask.projectId !== null &&
        p.superProductivityProjectId === spTask.projectId &&
        (p.kind ?? 'code') === 'code',
    )?.id ?? null;
  const source: SpNewTaskSource = {
    taskId: spTask.id,
    title: spTask.title.trim(),
    projectId: spTask.projectId,
  };
  setStore('newTaskDropUrl', null);
  setStore('newTaskPrefillPrompt', {
    prompt: buildPromptFromSpTask(spTask),
    name: source.title,
    projectId,
    superProductivity: source,
  });
  toggleNewTaskPanel(true);
}

/**
 * Link a task created from a Super Productivity task, and remember the
 * project pairing the user just made if the project had none.
 */
export function linkNewTaskToSp(taskId: string, source: SpNewTaskSource, projectId: string): void {
  const task = store.tasks[taskId];
  if (!task) return;
  const project = store.projects.find((p) => p.id === projectId);
  if (
    project &&
    !project.superProductivityProjectId &&
    source.projectId &&
    source.projectId !== SP_INBOX_PROJECT_ID
  ) {
    setProjectSpMapping(project.id, source.projectId);
  }
  if (task.nameIsAutoGenerated) {
    // The name field was cleared, so the form made one up. Record it as the
    // agreed title: the next sync then sees only Super Productivity's title
    // as changed and copies it here, instead of sending the made-up name.
    setSpLink(taskId, source.taskId, toSpTitle(task.name));
    return;
  }
  const title = toSpTitle(source.title);
  setSpLink(taskId, source.taskId, title);
  // A name edited in the form wins, like any other rename.
  if (toSpTitle(task.name) !== title) onTaskRenamed(taskId);
}

export function startSpOpenListener(): () => void {
  const consume = async (): Promise<void> => {
    const spTaskId = await invoke<string | null>(IPC.SuperProductivityConsumePendingOpen);
    if (spTaskId) await openNewTaskFromSp(spTaskId);
  };
  const run = () =>
    void consume().catch((err: unknown) => {
      logWarn('super-productivity', 'Could not open task from Super Productivity', {
        err: String(err),
      });
      showNotification('Could not open the task from Super Productivity');
    });
  const off = window.electron.ipcRenderer.on(IPC.SuperProductivityOpenTaskRequested, run);
  run();
  return off;
}
