// electron-builder afterPack hook (Linux).
//
// Fork direction (miadisabelle): Parallel Code is a trusted local dev tool that
// is frequently launched as root on headless servers. Chromium/Electron aborts
// with a FATAL "Running as root without --no-sandbox is not supported" — and
// that check runs in native code BEFORE any JS executes, so it cannot be fixed
// from inside the app's main process. The only reliable place to inject the flag
// is the launcher itself.
//
// We rename the real Electron executable to `<name>.bin` and drop a tiny wrapper
// in its place that always execs the real binary with `--no-sandbox`. Both the
// desktop entry and the `/usr/bin/<name>` alternative point at this wrapper, so
// icon launches and CLI launches (root or not) both work. `exec -a <name>`
// preserves argv[0] so the X11 window class still matches StartupWMClass.
//
// Resource resolution is unaffected: Electron locates resources.pak, snapshot
// blobs, locales/, resources/ and chrome_crashpad_handler relative to the
// executable's directory (via /proc/self/exe), not its filename — and `.bin`
// lives in that same directory.

const fs = require('fs');
const path = require('path');

exports.default = async function afterPack(context) {
  if (context.electronPlatformName !== 'linux') return;

  const dir = context.appOutDir;
  const name =
    context.packager.executableName || context.packager.appInfo.productFilename || 'parallel-code';

  const launcher = path.join(dir, name);
  const real = path.join(dir, `${name}.bin`);

  // Idempotent — a re-pack over the same dir must not double-wrap.
  if (fs.existsSync(real)) return;

  if (!fs.existsSync(launcher)) {
    throw new Error(`after-pack: expected Electron launcher not found at ${launcher}`);
  }

  fs.renameSync(launcher, real);

  const wrapper = `#!/bin/bash
# Auto-generated by scripts/after-pack.cjs — always launch with --no-sandbox.
# Chromium refuses to run as root without it, and the check fires before any JS.
HERE="$(dirname "$(readlink -f "$0")")"
exec -a "${name}" "$HERE/${name}.bin" --no-sandbox "$@"
`;

  fs.writeFileSync(launcher, wrapper, { mode: 0o755 });
  fs.chmodSync(launcher, 0o755);
};
